# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Larissa Carrer / %s"
og_image: /img/og_emma.png
author: Larissa Carrer
favicon: /img/favicon.jpg
description: Artesã e Personalisáveis
port: 8083

# OG image
origin: https://mfurquimdev.github.io/larissa-carrer
og: /img/og.jpg


navigation:
  header:
    - Larissa Carrer: /
    - Sobre mim: /about_me/
    - Orçamento: /contact/

  footer:
    - © Larissa Carrer: /

    - image: /img/github.svg
      url: //github.com/mfurquimdev/larissa-carrer
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/redatoracarrer/
      alt: LinkedIn profile
      size: 22 x 22
